--
-- PostgreSQL database dump
--


-- Dumped from database version 15.14 (Debian 15.14-1.pgdg13+1)
-- Dumped by pg_dump version 17.6 (Ubuntu 17.6-0ubuntu0.25.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_table_access_method = heap;

--
-- Name: goose_db_version; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.goose_db_version (
    id integer NOT NULL,
    version_id bigint NOT NULL,
    is_applied boolean NOT NULL,
    tstamp timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: goose_db_version_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.goose_db_version ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.goose_db_version_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: state; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.state (
    id uuid NOT NULL,
    idempotency_key text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    status integer NOT NULL,
    step text NOT NULL,
    type text NOT NULL,
    error text,
    data jsonb,
    fail_data jsonb,
    meta_data jsonb
);


--
-- Name: step_execute_info; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.step_execute_info (
    id integer NOT NULL,
    state_id uuid NOT NULL,
    start_executed_at timestamp with time zone NOT NULL,
    complete_executed_at timestamp with time zone NOT NULL,
    error text,
    preview_step text NOT NULL,
    next_step text
);


--
-- Name: step_execute_info_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.step_execute_info_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: step_execute_info_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.step_execute_info_id_seq OWNED BY public.step_execute_info.id;


--
-- Name: step_execute_info id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.step_execute_info ALTER COLUMN id SET DEFAULT nextval('public.step_execute_info_id_seq'::regclass);


--
-- Name: goose_db_version goose_db_version_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.goose_db_version
    ADD CONSTRAINT goose_db_version_pkey PRIMARY KEY (id);


--
-- Name: state state_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.state
    ADD CONSTRAINT state_pkey PRIMARY KEY (id);


--
-- Name: step_execute_info step_execute_info_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.step_execute_info
    ADD CONSTRAINT step_execute_info_pkey PRIMARY KEY (id);


--
-- Name: idx_state_idempotency_key; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_state_idempotency_key ON public.state USING btree (idempotency_key);


--
-- Name: idx_step_execute_state_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_step_execute_state_id ON public.step_execute_info USING btree (state_id);


--
-- Name: step_execute_info step_execute_info_state_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.step_execute_info
    ADD CONSTRAINT step_execute_info_state_id_fkey FOREIGN KEY (state_id) REFERENCES public.state(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--


