// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package statemachine

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type GooseDbVersion struct {
	ID        int
	VersionID int64
	IsApplied bool
	Tstamp    pgtype.Timestamp
}

type State struct {
	ID             uuid.UUID
	IdempotencyKey string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Status         int
	Step           string
	Type           string
	Error          *string
	Data           []byte
	FailData       []byte
	MetaData       []byte
}

type StepExecuteInfo struct {
	ID                 int
	StateID            uuid.UUID
	StartExecutedAt    time.Time
	CompleteExecutedAt time.Time
	Error              *string
	PreviewStep        string
	NextStep           *string
}
