// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package statemachine

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createState = `-- name: CreateState :exec
INSERT INTO state (id, idempotency_key, created_at, updated_at,
                   status, step, type, data, fail_data, meta_data)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type CreateStateParams struct {
	ID             uuid.UUID
	IdempotencyKey string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Status         int
	Step           string
	Type           string
	Data           []byte
	FailData       []byte
	MetaData       []byte
}

// ----------------------------------------------------------------------------------------------------------------------
func (q *Queries) CreateState(ctx context.Context, arg CreateStateParams) error {
	_, err := q.db.Exec(ctx, createState,
		arg.ID,
		arg.IdempotencyKey,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Status,
		arg.Step,
		arg.Type,
		arg.Data,
		arg.FailData,
		arg.MetaData,
	)
	return err
}

const getStateByID = `-- name: GetStateByID :one
SELECT id, idempotency_key, created_at, updated_at,
       status, step, type, data, fail_data, meta_data, error
FROM state
WHERE id = $1
LIMIT 1
`

type GetStateByIDRow struct {
	ID             uuid.UUID
	IdempotencyKey string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Status         int
	Step           string
	Type           string
	Data           []byte
	FailData       []byte
	MetaData       []byte
	Error          *string
}

func (q *Queries) GetStateByID(ctx context.Context, id uuid.UUID) (GetStateByIDRow, error) {
	row := q.db.QueryRow(ctx, getStateByID, id)
	var i GetStateByIDRow
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.Step,
		&i.Type,
		&i.Data,
		&i.FailData,
		&i.MetaData,
		&i.Error,
	)
	return i, err
}

const getStateByIdempotencyKey = `-- name: GetStateByIdempotencyKey :one
SELECT id, idempotency_key, created_at, updated_at,
       status, step, type, data, fail_data, meta_data, error
FROM state
WHERE idempotency_key = $1
LIMIT 1
`

type GetStateByIdempotencyKeyRow struct {
	ID             uuid.UUID
	IdempotencyKey string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Status         int
	Step           string
	Type           string
	Data           []byte
	FailData       []byte
	MetaData       []byte
	Error          *string
}

func (q *Queries) GetStateByIdempotencyKey(ctx context.Context, idempotencyKey string) (GetStateByIdempotencyKeyRow, error) {
	row := q.db.QueryRow(ctx, getStateByIdempotencyKey, idempotencyKey)
	var i GetStateByIdempotencyKeyRow
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.Step,
		&i.Type,
		&i.Data,
		&i.FailData,
		&i.MetaData,
		&i.Error,
	)
	return i, err
}

const getStepExecuteInfos = `-- name: GetStepExecuteInfos :many
SELECT
    state_id, start_executed_at, complete_executed_at,
    error, preview_step, next_step
FROM step_execute_info
WHERE state_id = $1
ORDER BY start_executed_at
`

type GetStepExecuteInfosRow struct {
	StateID            uuid.UUID
	StartExecutedAt    time.Time
	CompleteExecutedAt time.Time
	Error              *string
	PreviewStep        string
	NextStep           *string
}

func (q *Queries) GetStepExecuteInfos(ctx context.Context, stateID uuid.UUID) ([]GetStepExecuteInfosRow, error) {
	rows, err := q.db.Query(ctx, getStepExecuteInfos, stateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStepExecuteInfosRow
	for rows.Next() {
		var i GetStepExecuteInfosRow
		if err := rows.Scan(
			&i.StateID,
			&i.StartExecutedAt,
			&i.CompleteExecutedAt,
			&i.Error,
			&i.PreviewStep,
			&i.NextStep,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveStepExecuteInfo = `-- name: SaveStepExecuteInfo :exec

INSERT INTO step_execute_info (
    state_id, start_executed_at, complete_executed_at,
    error, preview_step, next_step
) VALUES ($1, $2, $3, $4, $5, $6)
`

type SaveStepExecuteInfoParams struct {
	StateID            uuid.UUID
	StartExecutedAt    time.Time
	CompleteExecutedAt time.Time
	Error              *string
	PreviewStep        string
	NextStep           *string
}

// ----------------------------------------------------------------------------------------------------------------------
func (q *Queries) SaveStepExecuteInfo(ctx context.Context, arg SaveStepExecuteInfoParams) error {
	_, err := q.db.Exec(ctx, saveStepExecuteInfo,
		arg.StateID,
		arg.StartExecutedAt,
		arg.CompleteExecutedAt,
		arg.Error,
		arg.PreviewStep,
		arg.NextStep,
	)
	return err
}

const updateState = `-- name: UpdateState :one
UPDATE state
SET
    updated_at = $1,
    status = $2,
    step = $3,
    data = $4,
    fail_data = $5,
    meta_data = $6,
    error = $7
WHERE id = $8
RETURNING id
`

type UpdateStateParams struct {
	UpdatedAt time.Time
	Status    int
	Step      string
	Data      []byte
	FailData  []byte
	MetaData  []byte
	Error     *string
	ID        uuid.UUID
}

func (q *Queries) UpdateState(ctx context.Context, arg UpdateStateParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, updateState,
		arg.UpdatedAt,
		arg.Status,
		arg.Step,
		arg.Data,
		arg.FailData,
		arg.MetaData,
		arg.Error,
		arg.ID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
